/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nats.io;

public class PlaceHolder {
    public PlaceHolder() {
        // THIS CLASS DOES NOTHING EXCEPT PUT SOME CODE IN THE PROJECT
    }
}
