/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.nats.integration.server.behavior;

import io.nats.client.JetStreamSubscription;
import io.nats.client.Message;
import io.nats.client.PushSubscribeOptions;
import io.nats.client.api.ConsumerConfiguration;
import io.nats.integration.utils.JetStreamTestBase;
import io.nats.integration.utils.JetStreamTestHelper;
import org.junit.jupiter.api.Test;

import java.time.Duration;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

class AckPolicy extends JetStreamTestBase {

    @Test
    public void testAckPolicy() throws Exception {
        runInJsServer(nc -> {
            JetStreamTestHelper h = createTestMemoryStream(nc);

            // AckPolicy.None
            ConsumerConfiguration cc = ConsumerConfiguration.builder().ackPolicy(io.nats.client.api.AckPolicy.None).build();
            PushSubscribeOptions pso = PushSubscribeOptions.builder().configuration(cc).build();
            JetStreamSubscription sub = h.js.subscribe(h.subject, pso);

            jsPublish(h.js, h.subject, 1);

            Message m = sub.nextMessage(Duration.ofMillis(1000));
            assertNotNull(m);
            assertEquals(0, sub.getConsumerInfo().getNumAckPending());
        });
    }
}