/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.nats.integration.server.prs;

import io.nats.integration.utils.JetStreamTestBase;
import io.nats.integration.utils.JetStreamTestHelper;
import org.junit.jupiter.api.Test;

import static io.nats.integration.utils.JetStreamTestBase.runInJsServer;

class Pr2152FileStreamDeleteTest {

    // https://github.com/nats-io/nats-server/pull/2152
    // On windows this failed to delete the stream b/c temporary files were left open.
    @Test
    void server_pr_2152_FileStreamDeleteTest() throws Exception {
        runInJsServer(nc -> {
            JetStreamTestHelper h = JetStreamTestBase.createTestFileStream(nc);
            nc.jetStream().publish(h.subject, new byte[1]);
            h.jsm.deleteStream(h.streamName);
        });
    }
}
