/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.nats.integration.server.prs;

import io.nats.client.JetStream;
import io.nats.client.JetStreamSubscription;
import io.nats.client.Message;
import io.nats.client.PullSubscribeOptions;
import io.nats.client.api.ConsumerConfiguration;
import io.nats.client.api.StorageType;
import io.nats.client.api.StreamConfiguration;
import io.nats.client.impl.NatsMessage;
import org.junit.jupiter.api.Test;

import java.time.Duration;

import static io.nats.integration.utils.JetStreamTestBase.runInJsServer;
import static io.nats.integration.utils.TestBase.sleep;
import static org.junit.jupiter.api.Assertions.assertNotNull;

public class Pr2832PullNoWaitRedeliverTest {

    // https://github.com/nats-io/nats-server/pull/2832
    // pull with no wait was not handling redelivers
    @Test
    public void testNoWaitRedeliver() throws Exception {
        runInJsServer(nc -> {

            StreamConfiguration sc = StreamConfiguration.builder()
                .name("nwr-strm")
                .storageType(StorageType.Memory)
                .subjects("nwr-sub").build();

            nc.jetStreamManagement().addStream(sc);

            // Create our JetStream context.
            JetStream js = nc.jetStream();
            js.publish(new NatsMessage("nwr-sub", null, null));

            ConsumerConfiguration cc = ConsumerConfiguration.builder()
                .ackWait(Duration.ofMillis(1000))
                .build();

            PullSubscribeOptions options = PullSubscribeOptions.builder()
                .durable("nwr-dur") // required
                .configuration(cc)
                .build();

            JetStreamSubscription sub = js.subscribe("nwr-sub", options);

            sub.pullNoWait(1);
            Message msg = sub.nextMessage(500);
            msg.nak();
            sleep(2000); // nak

            sub.pullNoWait(1);
            msg = sub.nextMessage(1000);
            assertNotNull(msg);
            sleep(2000); // don't ack

            sub.pullNoWait(1);
            msg = sub.nextMessage(1000);
            assertNotNull(msg);
            msg.ack();
        });
    }
}
