/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.nats.integration.client;

import io.nats.integration.utils.JetStreamTestBase;
import org.junit.jupiter.api.Test;

class ServerInfo extends JetStreamTestBase {

    @Test
    public void testGetServerInfo() throws Exception {
        runInJsServer(nc -> {
            printFormatted(nc.getServerInfo());
        });
    }
}