name: Ubuntu Go Client Tests
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  ubuntu-go-client-tests:
    runs-on: ubuntu-latest
    env:
      GODEBUG: x509sha1=1
    steps:
      - name: Setup GO
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.4'
      - name: Install nats-server
        run: |
          curl -sf https://binaries.nats.dev/nats-io/nats-server/v2@main | PREFIX=. sh
          sudo mv nats-server /usr/local/bin
          nats-server -v
      - name: Check out Go client code
        uses: actions/checkout@v3
        with:
          repository: nats-io/nats.go
      - name: Go Get Stuff
        run: |
          go get -t ./...
          go get github.com/mattn/goveralls
          go get github.com/wadey/gocovmerge
          go get -u honnef.co/go/tools/cmd/staticcheck
          go get -u github.com/client9/misspell/cmd/misspell
          go get -modfile go_test.mod github.com/nats-io/nats-server/v2@main
      - name: Run No Race Tests
        run: go test -v -p=1 -run=TestNoRace ./... -count=1 -vet=off -timeout=30m -failfast
      - name: Run JS Tests
        run: go test -race -v -run=TestJetStream ./server -tags=skip_js_cluster_tests,skip_js_cluster_tests_2,skip_js_cluster_tests_3,skip_js_super_cluster_tests -count=1 -vet=off -timeout=30m -failfast
