name: Windows Go Client Tests
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  windows-go-client-tests:
    runs-on: windows-latest
    steps:
      - name: Setup GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6
      - name: Install Nats Server
        uses: scottf/install-nats-io-server-windows@main
      - name: Check out Go client code
        uses: actions/checkout@v2
        with:
          repository: nats-io/nats.go
      - name: Run Client Unit Tests
        run: go test -modfile=go_test.mod -v -p=1 ./...
        shell: cmd
