name: Windows Go Client Tests
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  windows-go-client-tests:
    runs-on: windows-latest
    env:
      GODEBUG: x509sha1=1
    steps:
      - name: Setup GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.2
      - name: Install Nats Server
        run: |
          git clone https://github.com/nats-io/nats-server.git
          cd nats-server
          go get
          go build main.go
          copy /Y main.exe ..\nats-server.exe
          cd ..
          rd /S /Q nats-server
          nats-server -v
        shell: cmd
      - name: Check out Go client code
        uses: actions/checkout@v2
        with:
          repository: nats-io/nats.go
      - name: Go Get Stuff
        run: |
          go get -t ./...
          go get github.com/mattn/goveralls
          go get github.com/wadey/gocovmerge
          go get -u honnef.co/go/tools/cmd/staticcheck
          go get -u github.com/client9/misspell/cmd/misspell
        shell: cmd
      - name: Run Client Unit Tests
        run: go test -modfile=go_test.mod -v -run=TestNoRace -p=1 ./... --failfast -vet=off
        shell: cmd
