name: Ubuntu Go Client Tests
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  ubuntu-go-client-tests:
    runs-on: ubuntu-latest
    env:
      GODEBUG: x509sha1=1
    steps:
      - name: Setup GO
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.8'
      - name: Install nats-server
        run: |
          curl -sf https://binaries.nats.dev/nats-io/nats-server/v2@main | PREFIX=. sh
          sudo mv nats-server /usr/local/bin
          nats-server -v
      - name: Check out Go client code
        uses: actions/checkout@v3
        with:
          repository: nats-io/nats.go
      - name: Go Get Stuff
        run: |
          go get -t ./...
          go get github.com/mattn/goveralls
          go get github.com/wadey/gocovmerge
          go get -u honnef.co/go/tools/cmd/staticcheck
          go get -u github.com/client9/misspell/cmd/misspell
      - name: Run Client Unit Tests
        run: go test -modfile=go_test.mod -v -run=TestNoRace -p=1 ./... --failfast -vet=off
