name: Windows Integration Tests
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  windows-integration-tests:
    runs-on: windows-latest
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Setup GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3
      - name: Install Nats Server
        uses: scottf/install-nats-io-server-windows@v1
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run Java Integration Tests
        run: |
          cd java-integration-tests
          gradlew -i test
          cd ..
        shell: cmd
