name: Ubuntu Integration Tests
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  ubuntu-integration-tests:
    runs-on: ubuntu-latest
    env:
      GODEBUG: x509sha1=1
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Install nats-server
        run: |
          curl -sf https://binaries.nats.dev/nats-io/nats-server/v2@main | PREFIX=. sh
          sudo mv nats-server /usr/local/bin
          nats-server -v
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run Java Integration Tests
        run: |
          pushd java-integration-tests
          chmod +x gradlew
          ./gradlew test
          popd
