name: Windows Integration Tests
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  windows-integration-tests:
    runs-on: windows-latest
    env:
      GODEBUG: x509sha1=1
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Setup GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.1
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run Java Integration Tests
        run: |
          cd %GITHUB_WORKSPACE%\java-integration-tests
          call ..\install-server latest
          gradlew.bat clean test
        shell: cmd
      - name: Run Server Behavior By Version 2.7.1
        run: |
          cd %GITHUB_WORKSPACE%\java-integration-tests
          call ..\install-server v2.7.1
          gradlew.bat clean test --tests io.nats.integration.client.ServerBehaviorByVersion
        shell: cmd
      - name: Run Server Behavior By Version 2.8.4
        run: |
          cd %GITHUB_WORKSPACE%\java-integration-tests
          call ..\install-server v2.8.4
          gradlew.bat clean test --tests io.nats.integration.client.ServerBehaviorByVersion
        shell: cmd
      - name: Run Server Behavior By Version 2.9.0
        run: |
          cd %GITHUB_WORKSPACE%\java-integration-tests
          call ..\install-server v2.9.0
          gradlew.bat clean test --tests io.nats.integration.client.ServerBehaviorByVersion
        shell: cmd
