name: GitHub Pull Request Actions For Nats Server Runner
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      nats_server_path: ../nats-server/main
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Setup GO
        uses: actions/setup-go@v2
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Nats Server
        run: chmod +x install-nats-server.sh && ./install-nats-server.sh
      - run: ls -la
      - run: pwd
      - run: echo $HOME
      - run: printenv | sort
      - name: Run Java Integration Tests
        run: cd java-integtration-tests && chmod +x gradlew && ./gradlew test
