name: Integration Tests
on:
  schedule:
    - cron: "10 14 * * *"
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    env:
      nats_server_path: "/home/runner/nats-server/main"
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Setup GO
        uses: actions/setup-go@v2
      - name: Install Nats Server
        run: |
          date
          pushd ~
          git clone https://github.com/nats-io/nats-server.git
          cd nats-server
          go build main.go
          popd
          eval $nats_server_path -v
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run Java Integration Tests
        run: |
          pushd java-integration-tests
          chmod +x gradlew
          ./gradlew test
          popd
