name: Windows Integration Tests
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  windows-integration-tests:
    runs-on: windows-latest
    env:
      GODEBUG: x509sha1=1
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Setup GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.1
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Nats Server
        run: |
          git clone https://github.com/nats-io/nats-server.git
          cd nats-server
          go get
          go build main.go
          copy /Y main.exe ..\java-integration-tests\nats-server.exe
          cd ..
          rd /S /Q nats-server
          java-integration-tests\nats-server -v
        shell: bash
      - name: Run Java Integration Tests
        run: |
          cd java-integration-tests
          gradlew.bat test
        shell: cmd
