name: GitHub Pull Request Actions For Nats Server Runner
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      nats_server_path: "$HOME/nats-server/main"
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Setup GO
        uses: actions/setup-go@v2
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Nats Server
        run: |
          cd ~
          git clone https://github.com/nats-io/nats-server.git
          cd nats-server
          go build main.go
          cd ~
          nats-server/main -v
      - name: Run Java Integration Tests
        run: |
          cd ~/integration-tests/java-integtration-tests
          chmod +x gradlew
          ./gradlew test
