name: Windows Java Client Tests
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  windows-java-client-tests:
    runs-on: windows-latest
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Setup GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6
      - name: Install Nats Server
        uses: scottf/install-nats-io-server-windows@main
      - name: Check out Java client code
        uses: actions/checkout@v2
        with:
          repository: nats-io/nats.java
      - name: Run Client Unit Tests
        run: gradlew.bat test
        shell: cmd
