name: Ubuntu Java Client Tests
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  ubuntu-java-client-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Setup GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3
      - name: Install Nats Server
        uses: scottf/install-nats-io-server-ubuntu@v1
      - name: Check out Java client code
        uses: actions/checkout@v2
        with:
          repository: nats-io/nats.java
      - name: Run Client Unit Tests
        run: chmod +x gradlew && ./gradlew test
