name: Windows Java Client Tests dev Branch Server
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  windows-java-client-tests:
    runs-on: windows-latest
    env:
      GODEBUG: x509sha1=1
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Setup GO
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.8'
      - name: Check out Java client code
        uses: actions/checkout@v3
        with:
          repository: nats-io/nats.java
      - name: Install Nats Server
        run: |
          git clone https://github.com/nats-io/nats-server.git
          cd nats-server
          git checkout dev
          go get
          go build main.go
          copy /Y main.exe ..\nats-server.exe
          cd ..
          rd /S /Q nats-server
          nats-server -v
        shell: cmd
      - name: Run Client Unit Tests
        run: gradlew.bat test
        shell: cmd
