name: Ubuntu Java Client Tests v2.8.4 Server
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  ubuntu-java-client-regression-tests-284:
    runs-on: ubuntu-latest
    env:
      GODEBUG: x509sha1=1
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Install nats-server
        run: |
          curl -sf https://binaries.nats.dev/nats-io/nats-server/v2@v2.8.4 | PREFIX=. sh
          nats-server -v
      - name: Check out Java client code
        uses: actions/checkout@v2
        with:
          repository: nats-io/nats.java
      - name: Run Client Unit Tests
        run: chmod +x gradlew && ./gradlew test
